### ISSUE TITLE
Mage does not work with newer .NET Framework version

### ISSUE THREAD

**Issue by sierzput** [enkafan/Cake.Mage#14]
When only .NET Framework 4.7.2 is installed Cake.Mage tool cannot find mage.exe file. It would be nice to have a generic way to resolve tool path rather than have all possible paths hardcoded.

**Comment by MihaMarkic** [comment]
@sierzput  Can you test it with recently released 0.4.0?

**Comment by MihaMarkic** [comment]
Merged your PR https://github.com/cake-contrib/Cake.Mage/pull/13/commits/827c87d7324ed551d25f5225fe737e738722d235
