### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [enkafan/Cake.Mage#2]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by phil-scott-78** [comment]
@gep13  - with this in a prerelease state I was going to hold off for now. Although it would be great if the add-in list had the ability to mark this as pre-release or beta so I could get feedback from others. I'm only going to be able to test my very narrow workflow with the Mage tool so I'm sure there would be bugs galore and I wouldn't want to list it without expectations being set properly.

**Comment by gep13** [comment]
@enkafan makes sense to me!

Could you raise an issue about this on the website repo?  This seems like a good idea to me.
