### ISSUE TITLE
Setup.exe

### ISSUE THREAD

**Issue by wahmedswl** [enkafan/Cake.Mage#3]
Hi,
   Setup.exe which is generated when published from Visual Studio doesn't get generated using Mage, is there something i am missing in configuration?

Thanks

**Comment by phil-scott-78** [comment]
So Mage doesn't do the setup.exe part - that's another task that's ran by VS and MSBuild.

Honestly we don't build a setup.exe for our apps so I'm not terribly familiar with the processes involved there, but if I was going to build a setup using cake I'd go right to WiX. Another approach might be to use a custom MSBuild script to call [`GenerateBootstrapper`](https://msdn.microsoft.com/en-us/library/ms164294.aspx). At that point I'd even think about going the full nine and using MSBuild to call Mage too. Might be easier than trying to get the two to play nicely.
