### ISSUE TITLE
Launcher should specified for .net3+ builds

### ISSUE THREAD

**Issue by unseensenpai** [enkafan/Cake.Mage#31]
Mage.exe is updated by dotnet. Dotnet-Mage.exe used on operations. And it requires launcher specification by [https://github.com/dotnet/deployment-tools/blob/main/docs/dotnet-mage/README.md#dotnet-mage](url)
## Expected Behavior

Launcher should specified to command line builder for deployment operation.

MageSign operation or specific updated operation should -al (add launcher) and -td (target directory) options.

## Current Behavior

Cannot create click once because of launcher.exe not exist. Manifest goes with exception inside.

Just imput -al and -td append side.

## Possible Solution

I made another method for cake context.

```
/// <summary>
/// .Net6 or later programs need launcher implementation. 
/// Need entry point dll or exe file path 
/// and target directory to create it.
/// </summary>
/// <param name="context"></param>
/// <param name="settings"></param>
```

I have created Mage Settings for update.
```
/// <summary>
/// Class SignSettings.
/// </summary>
/// <seealso cref="Cake.Core.Tooling.ToolSettings" />
public class LauncherSettings : BaseNewAndUpdateMageSettings
{
    
    /// <summary>
    /// Gets or sets the launcher exe's folder.
    /// </summary>
    /// <value>To file.</value>
    public DirectoryPath TargetDirectory { get; set; }

    /// <summary>
    /// Launchers entry point is DLL or EXE for .net6+ UI projects.
    /// </summary>
    public string LauncherEntryPoint { get; set; }
}
```

Now new and update tool can be handle this settings:

NewOrUpdateMageTool.cs
```
else
{
    var launcherSettings = (LauncherSettings)settings;
    if (launcherSettings is null || string.IsNullOrWhiteSpace(launcherSettings.LauncherEntryPoint) || launcherSettings.TargetDirectory is null)
    {
        ArgumentNullException.ThrowIfNull(nameof(launcherSettings));
    }
    return builder
            //.Append("mage")
            .AppendNonNullFileNameSwitch("-al", launcherSettings.LauncherEntryPoint, Environment)
            .AppendNonNullDirectoryPathSwitch("-td", launcherSettings.TargetDirectory, Environment);
}
```

```
[CakeMethodAlias]
public static void MageAddLauncher(this ICakeContext context, LauncherSettings settings)
{
    if (settings == null) throw new ArgumentNullException(nameof(settings));

    NewOrUpdate(context, settings);

}
```
MageRunner.cs should dotnet-mage.exe
![image](https://github.com/user-attachments/assets/3bad4dcf-4ac6-42fb-98fd-1bc752a9d30d)

Dotnet Tool Resolver should have dotnet-mage.exe path
```
var userProfilePath = _environment.GetSpecialPath(SpecialPath.UserProfile);
    var files = new List<FilePath>
    {
        // 64-bit
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Windows Kits\8.1\bin\x64").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Windows Kits\8.0\bin\x64").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine(@"Microsoft SDKs\Windows\v7.1A\Bin").CombineWithFilePath(toolExecutable),
        programFiles64Bit.Combine("dotnet").CombineWithFilePath(toolExecutable),
        userProfilePath.Combine(@".dotnet\tools").CombineWithFilePath(toolExecutable),

        // x86
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Windows Kits\8.1\bin\x86").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Windows Kits\8.0\bin\x86").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine(@"Microsoft SDKs\Windows\v7.1A\Bin").CombineWithFilePath(toolExecutable),
        programFilesX86.Combine("dotnet").CombineWithFilePath(toolExecutable),
        userProfilePath.Combine(@".dotnet\tools").CombineWithFilePath(toolExecutable)
};
```

So cake script can call like this:

```
MageAddLauncher(new LauncherSettings{
			LauncherEntryPoint = "Winform.UI.Project.Container.exe",
			TargetDirectory = localPublishFolder
		});

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version used:
* Operating System and PowerShell version:

**Comment by MihaMarkic** [comment]
Hi, you did a nice research. However, there is the problem of discovering executable. First, the old and new are differently named (mage.exe vs dotnet-mage.exe). I'd say there should be a version 2 of this plugin that ditches the old one and embraces only dotnet way.
People with legacy mage can still use version 1.x.

**Comment by MihaMarkic** [comment]
Pushed branch `feature/dotnetmage` with prototype based on your work. Would you mind checking it out?

**Comment by unseensenpai** [comment]
Seems like its working.

![image](https://github.com/user-attachments/assets/38976b68-4c18-42c2-8593-470a8845fdcc)

I tried on someshitty project cant confirm fully executable but there is a launcher.exe.

About dotnet-mage vs mage.exe, if there is no manifest problem go ahead.

Thanks for update.

**Comment by MihaMarkic** [comment]
What manifest problem did you have in mind?

**Comment by unseensenpai** [comment]
There is a entryPoint brackets(xml node parent) in exe.manifest for click once operation.

![image](https://github.com/user-attachments/assets/808cc36d-0380-4ab0-9dcd-2f569a2b1104)

I didnt try that with other type of .net projects (like WPF, WinForms)

Should tested but documentation says it will work:
![image](https://github.com/user-attachments/assets/da98c6fe-1eff-4fdd-9b60-c972a7452e53)

So if cake mage consumers writes scripts in a correct order that works like in screenshot .net says.

The Correct Order Is:

MageAddLauncher()  // Launcher Settings -> Launcher Entry Point (exe or dll) and Target Directory (deployment directory)
MageNewApplication() // Application Settings
MageSign() // Sign Settings -> Manifest File -> Cert File
MageNewDeployment // Deployment Settings -> Manifest File -> Application File
MageSign() // Sign Settings -> Application File -> Cert File

And its done.

**Comment by MihaMarkic** [comment]
At the end of the day Cake.Mage would merely invoke dotnet-mage tool, so I guess the addin itself can't deal with these issues?

**Comment by MihaMarkic** [comment]
@unseensenpai shall I close the issue and release 2.0.0?

**Comment by unseensenpai** [comment]
> @unseensenpai shall I close the issue and release 2.0.0?

Yep please, sorry i was busy with work. Thanks.
