### ISSUE TITLE
Cake.recipe fails

### ISSUE THREAD

**Issue by MihaMarkic** [enkafan/Cake.Mage#32]
Cake.recipe doesn't work, @gep13 can you take a look, please?

**Comment by gep13** [comment]
@MihaMarkic I have made a couple of commits on the develop branch, which I believe address the issues that you were seeing.

**Comment by MihaMarkic** [comment]
I guess .NET SDKs < 8 can be removed from appveyor as well, since adding doesn't target them?

**Comment by gep13** [comment]
You might be able to remove some of them, but there are some older tools used in Cake.Recipe that need some older frameworks. You would have to test to see what is needed and what isn't.
